In [245]:
import plotly.express as px
import plotly.offline as py
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sns; sns.set_theme()
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from datetime import datetime
import math
from scipy import stats
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime

pd.options.display.max_colwidth = 100

In [246]:
# Replace the file path with the path to your .csv file in your documents.
#caminho_arquivo = 'C:/Users/andre.santos/Segfy/B0.csv'
caminho_arquivo = 'C:/Users/JOSE/2022-10-03.csv'

# Use the read_csv function to read the file and store it in a DataFrame.
df = pd.read_csv(caminho_arquivo)

# Print the DataFrame to verify if the file was read correctly.
print(df)

C:\Users\JOSE\AppData\Local\Temp\ipykernel_18908\853663778.py:6: DtypeWarning:

Columns (26,100,101) have mixed types. Specify dtype option on import or set low_memory=False.

        id_cotacao                           grupo_calculo   preco_id  \
0         13296967  0013296967-1664831874-5127bd118ec1b3f9  327535619
1         13296967  0013296967-1664831874-5127bd118ec1b3f9  327535618
2         13296967  0013296967-1664831874-5127bd118ec1b3f9  327535752
3         13296967  0013296967-1664831874-5127bd118ec1b3f9  327535661
4         13296967  0013296967-1664831874-5127bd118ec1b3f9  327535721
...            ...                                     ...        ...
249774    18732356  0018732356-1664852243-3e8f69f43bbb364b  327556565
249775    18732356  0018732356-1664852243-3e8f69f43bbb364b  327556567
249776    18732356  0018732356-1664852243-3e8f69f43bbb364b  327556566
249777    18732356  0018732356-1664852243-3e8f69f43bbb364b  327556569
249778    18732356  0018732356-1664852243-3e8f69f43bbb364b  327556560

        cobertura_id  usuario_id  corretora_id  cliente_id  ranking  \
0           16830520       14688          7799     1392675        1
1           16830520       14688          7799     1392675        2
2           16830520       14688          7799     1392675        3
3           16830520       14688          7799     1392675        4
4           16830520       14688          7799     1392675        5
...              ...         ...           ...         ...      ...
249774      16831453       35299         22327     6801463        6
249775      16831453       35299         22327     6801463        7
249776      16831453       35299         22327     6801463        8
249777      16831453       35299         22327     6801463        9
249778      16831453       35299         22327     6801463       10

        REFERENCIA  tempo  ... danos_morais_premio isencao_franquia  \
0               61      3  ...                 NaN            False
1               61      3  ...                 NaN            False
2               27     27  ...               16,53            False
3               18      7  ...              133,32            False
4               22     17  ...                 NaN            False
...            ...    ...  ...                 ...              ...
249774          12     25  ...                 NaN            False
249775          12     25  ...                 NaN            False
249776          12     25  ...                 NaN            False
249777          13     39  ...                 NaN            False
249778          22     18  ...                 NaN            False

       franquia_retorno franquia_valor comissao comissao_retorno  \
0            reduzida50              0       15               15
1            reduzida50              0       15               15
2            reduzida50        5584,59       15               15
3            reduzida50        5279,48       15               15
4            reduzida50        4499,62       15               15
...                 ...            ...      ...              ...
249774       reduzida50        2448,36       20               20
249775       reduzida50        2448,36       20               20
249776       reduzida50        2448,36       20               20
249777       reduzida50           3928       20               20
249778       reduzida50         4029,1       20               20

                                                                                                        msg  \
0       <b>Cobertura:</b> Exclusiva para Indenização Integral por Roubo/Furto<br><b>Exclusões:</b> Não h...
1       <b>Cobertura:</b> Exclusiva para Indenização Integral por Roubo/Furto<br><b>Exclusões:</b> Não h...
2       As coberturas <b>Carta Verde</b> e <b>Extensão de Perímetro</b> foram contratadas por padrão par...
3       Ajuste de vigencia retroativa. 28/09/2022 -> 03/10/2022<br>Ajuste de vigencia menor de 365 dias....
4                                                                         Cálculo efetuado com successo<br>
...                                                                                                     ...
249774                                                                 Chassi decodificado com sucesso!<br>
249775                                                                 Chassi decodificado com sucesso!<br>
249776                                                                 Chassi decodificado com sucesso!<br>
249777  As informações de CPF/CNPJ, placa e chassi são necessárias para a análise de aceitação do cálcul...
249778                                                                    Cálculo efetuado com successo<br>

                                                                                                 msg_ajuste  \
0       Fipe ajustado para 95% conforme validação da CIA<br><b>Assistência 24Hrs/Reboque</b> foi ajustad...
1       Fipe ajustado para 95% conforme validação da CIA<br><b>Assistência 24Hrs/Reboque</b> foi ajustad...
2       <b>Atenção!</b> A vigência do seguro informada é inválida, ajustada para 03/10/2022 à 03/10/2023...
3       <a  target='_blank'> <b>Request</b></a><br><a  target='_blank'> <b>Response</b></a><br>O <b>iníc...
4       - A categoria anti-furto <b>Alarme</b> não é comercializada por esta CIA, cálculo efetuado sem a...
...                                                                                                     ...
249774  Foi selecionada a opção <b>Assist. Dia/Noite Ilimitado (108)</b> para a cobertura de <b>Assistên...
249775  Foi selecionada a opção <b>Assist. Dia/Noite Ilimitado (108)</b> para a cobertura de <b>Assistên...
249776  Foi selecionada a opção <b>Assist. Dia/Noite Ilimitado (108)</b> para a cobertura de <b>Assistên...
249777     Foi selecionada a opção <b>SUPERIOR</b> para a cobertura de <b>Assistência 24Hrs/Reboque</b><br>
249778  <b>Assistência 24Hrs/Reboque</b> foi ajustada de <b>Sem Limites</b> para <b>VIP KM ilimitado </b...

       Unnamed: 100 Unnamed: 101
0               NaN          NaN
1               NaN          NaN
2               NaN          NaN
3               NaN          NaN
4               NaN          NaN
...             ...          ...
249774          NaN          NaN
249775          NaN          NaN
249776          NaN          NaN
249777          NaN          NaN
249778          NaN          NaN

[249779 rows x 102 columns]

In [247]:
df.head(3)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,danos_morais_premio,isencao_franquia,franquia_retorno,franquia_valor,comissao,comissao_retorno,msg,msg_ajuste,Unnamed: 100,Unnamed: 101
0,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535619,16830520,14688,7799,1392675,1,61,3,...,NaN,False,reduzida50,0,15,15,<b>Cobertura:</b> Exclusiva para Indenização Integral por Roubo/Furto<br><b>Exclusões:</b> Não h...,Fipe ajustado para 95% conforme validação da CIA<br><b>Assistência 24Hrs/Reboque</b> foi ajustad...,NaN,NaN
1,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535618,16830520,14688,7799,1392675,2,61,3,...,NaN,False,reduzida50,0,15,15,<b>Cobertura:</b> Exclusiva para Indenização Integral por Roubo/Furto<br><b>Exclusões:</b> Não h...,Fipe ajustado para 95% conforme validação da CIA<br><b>Assistência 24Hrs/Reboque</b> foi ajustad...,NaN,NaN
2,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535752,16830520,14688,7799,1392675,3,27,27,...,"16,53",False,reduzida50,"5584,59",15,15,As coberturas <b>Carta Verde</b> e <b>Extensão de Perímetro</b> foram contratadas por padrão par...,"<b>Atenção!</b> A vigência do seguro informada é inválida, ajustada para 03/10/2022 à 03/10/2023...",NaN,NaN

In [248]:
# Get the total number of rows in the DataFrame.
total_linhas = df.shape[0]

# Get the number of distinct values in each column.
quantidade_distintos = df.nunique()

print(f'Quantidade total de linhas: {total_linhas}')
print('Quantidade de valores distintos por coluna:')
print(quantidade_distintos)

Quantidade total de linhas: 249779
Quantidade de valores distintos por coluna:
id_cotacao           14029
grupo_calculo        21301
preco_id            249779
cobertura_id         14919
usuario_id            3204
                     ...
comissao_retorno        32
msg                   1746
msg_ajuste            3736
Unnamed: 100             5
Unnamed: 101             4
Length: 102, dtype: int64

In [249]:
df.columns

Index(['id_cotacao', 'grupo_calculo', 'preco_id', 'cobertura_id', 'usuario_id',
       'corretora_id', 'cliente_id', 'ranking', 'REFERENCIA', 'tempo',
       ...
       'danos_morais_premio', 'isencao_franquia', 'franquia_retorno',
       'franquia_valor', 'comissao', 'comissao_retorno', 'msg', 'msg_ajuste',
       'Unnamed: 100', 'Unnamed: 101'],
      dtype='object', length=102)

In [250]:
# Filter Data Frame
df_filtered = df.filter(items = ['id_cotacao',
                                 'grupo_calculo',
                                 'preco_id',
                                 'cobertura_id',
                                 'usuario_id',
                                 'corretora_id',
                                 'cliente_id',
                                 'ranking',
                                 'REFERENCIA',
                                 'tempo',
                                 'produto',
                                 'tiposeguro',
                                 'seguradora_renovacao',
                                 'renovacao_propria',
                                 'datacalculo',
                                 'datahoracalculo',
                                 'dataresultado',
                                 'inicio_vigencia',
                                 'termino_vigencia',
                                 'tipo_cobertura',
                                 'tipo_cobertura_retorno',
                                 'tipofranquia',
                                 'danos_materiais',
                                 'danos_corporais',
                                 'danos_morais',
                                 'morte',
                                 'invalidez',
                                 'despesas_extraordinarias',
                                 'coberturas_vidros',
                                 'coberturas_vidros_retorno',
                                 'coberturas_17a25anos',
                                 'cobertura_para_outro_condutor',
                                 'coberturas_assistencia',
                                 'coberturas_carroreserva',
                                 'carro_reserva_retorno',
                                 'perfil_carro_reserva',
                                 'assistencias_km',
                                 'assistencia_24h_retorno',
                                 'dias_carro_reserva',
                                 'segurado_sexo',
                                 'segurado_estadocivil',
                                 'segurado_data_nascimento',
                                 'segurado_cep',
                                 'condutor_data_habilitacao',
                                 'relacao_cliente_condutor',
                                 'profissao_condutor_principal',
                                 'condutor_tipo_de_residencia',
                                 'codigo_fipe',
                                 'ano_fab',
                                 'ano_modelo',
                                 'zero_km',
                                 'percentual_fipe_retorno',
                                 'marcas_tipo',
                                 'tipo_veiculo',
                                 'fabricante',
                                 'modelo',
                                 'categoria_anti_furto',
                                 'marca_anti_furto',
                                 'alienado',
                                 'chassi_remarcado',
                                 'tipo_combustivel',
                                 'valor_kit_gas',
                                 'veiculo_blindado',
                                 'valor_blindado',
                                 'isencao_fiscal',
                                 'veiculo_retorno',
                                 'bonus_atual',
                                 'bonus_anterior',
                                 'vitima_furto',
                                 'qtd_sinistros',
                                 'cep_pernoite',
                                 'cep_circula',
                                 'distancia_residencia_trabalho',
                                 'carros_residencia',
                                 'garagem_residencia',
                                 'garagem_trabalho',
                                 'garagem_estudo',
                                 'utilizacao_veiculo',
                                 'km_mensal',
                                 'reposicao_zero_km',
                                 'oficina_retorno',
                                 'status',
                                 'premio_bruto',
                                 'premio_liquido',
                                 'danos_corporais_premio',
                                 'danos_materiais_premio',
                                 'danos_morais_premio',
                                 'isencao_franquia',
                                 'franquia_retorno',
                                 'comissao_retorno'])



df_filtered.head(3)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,oficina_retorno,status,premio_bruto,premio_liquido,danos_corporais_premio,danos_materiais_premio,danos_morais_premio,isencao_franquia,franquia_retorno,comissao_retorno
0,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535619,16830520,14688,7799,1392675,1,61,3,...,NaN,OK,"1823,99","1698,63",NaN,NaN,NaN,False,reduzida50,15
1,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535618,16830520,14688,7799,1392675,2,61,3,...,NaN,PRODUTO_ADICIONAL,"3068,24","2857,37",NaN,NaN,NaN,False,reduzida50,15
2,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535752,16830520,14688,7799,1392675,3,27,27,...,NaN,OK,"4228,65","3938,02","34,45","386,14","16,53",False,reduzida50,15

In [251]:
#new DF
df_improved = df_filtered

#Row 'date diff' = vigencia
df_improved['inicio_vigencia'] = pd.to_datetime(df_improved['inicio_vigencia'], errors = 'coerce', infer_datetime_format=True)
df_improved['termino_vigencia'] = pd.to_datetime(df_improved['termino_vigencia'], errors = 'coerce', infer_datetime_format=True)
df_improved = df_improved.assign(date_diff=(df_improved['termino_vigencia'] - df_improved['inicio_vigencia']).dt.days)

In [252]:
def verifica_contratacao(valor):
    nao_contratado = ['Não contratado', 'NÃ£o possui Cobertura', 'não Contratada', 'NÃ£o Contempla', 'NÃ£o contemplado', 'NÃ£o Contratado', 'Sem carro reserva']
    if valor in nao_contratado:
        return 'Não'
    else:
        return 'Sim'

df_improved['vidros_sim'] = df_improved['coberturas_vidros_retorno'].apply(verifica_contratacao)
df_improved['carro_reserva_sim'] = df_improved['carro_reserva_retorno'].apply(verifica_contratacao)
df_improved['assistencia_24h_sim'] = df_improved['assistencia_24h_retorno'].apply(verifica_contratacao)

def validar_assistencias(row):
    if 'Sim' in row.values:  # If 'Sim' is present in any column
        return 'Sim'
    else:
        return 'Não'

df_improved['assistencias_total'] = df_improved[['vidros_sim', 'carro_reserva_sim', 'assistencia_24h_sim']].apply(validar_assistencias, axis=1)

# Validate
df_improved[['coberturas_vidros_retorno', 'vidros_sim', 'carro_reserva_retorno', 'carro_reserva_sim', 'assistencia_24h_retorno', 'assistencia_24h_sim', 'assistencias_total']].head(10)

,coberturas_vidros_retorno,vidros_sim,carro_reserva_retorno,carro_reserva_sim,assistencia_24h_retorno,assistencia_24h_sim,assistencias_total
0,Não contratado,Não,Não contratado,Não,"200KM, Taxi, Chaveiro, Troca de Pneus",Sim,Sim
1,Não contratado,Não,Não contratado,Não,"200KM, Taxi, Chaveiro, Troca de Pneus",Sim,Sim
2,Vidros - Cobertura Completa,Sim,NaN,Sim,Guincho 400 km,Sim,Sim
3,"HDI Auto Vidros, Faróis, Lanternas, Retrovisores e Auxiliar",Sim,Sem carro reserva,Não,Guincho 200 KM,Sim,Sim
4,Completo Rede Referenciada,Sim,Carro Reserva não coletado,Sim,Completo 500km,Sim,Sim
5,Vidro Protegido Plus (024),Sim,Não desejo contratar,Sim,Assist Dia/Noite 200Km (043),Sim,Sim
6,Vidro Protegido (025),Sim,Auto Reserva 07 Dias (060),Sim,Assist Dia/Noite 400Km (113),Sim,Sim
7,Vidros Completo - Rede Referenciada,Sim,Não Contratado,Sim,Assist. 24h Completo - 200km,Sim,Sim
8,"HDI Auto Vidros, Faróis, Lanternas, Retrovisores e Auxiliar",Sim,Sem carro reserva,Não,Guincho 200 KM,Sim,Sim
9,Vidros Completa,Sim,07 dias com ar condicionado,Sim,Reboque Adicional de 200 Km,Sim,Sim

In [253]:
#new DF
df_improved2 = df_improved

#generate 'faixa_de_edade'
df_improved2['segurado_data_nascimento'] = pd.to_datetime(df_improved2['segurado_data_nascimento'], infer_datetime_format=True)

data_atual = datetime.now()
df_improved2['idade'] = (data_atual - df_improved2['segurado_data_nascimento']).astype('<m8[Y]')

def faixa_idade_range(valor):
    if valor < 17:
        return '1 a 16'
    elif valor < 27:
        return '17 a 26'
    elif valor < 37:
        return '27 a 36'
    elif valor < 47:
        return '37 a 46'
    elif valor < 57:
        return '47 a 56'
    elif valor < 67:
        return '57 a 66'
    elif valor < 77:
        return '67 a 76'
    else:
        return '77 +'
    
df_improved2['faixa_idade'] = df_improved2['idade'].apply(faixa_idade_range)


#generate 'faixa_de_edade_carro'

df_improved2['ano_modelo'] = df_improved2['ano_modelo'].astype(str)
df_improved2['ano_modelo'] = df_improved2['ano_modelo'].astype(int)
df_improved2['idade_carro'] = 2023 - df_improved2['ano_modelo']



def faixa_idade_carro_range(valor):
    if valor < 2:
        return '0 a 1,9 anos'
    elif valor < 4:
        return '2 a 3,9 anos'
    elif valor < 6:
        return '4 a 5,9 anos'
    elif valor < 8:
        return '6 a 7,9 anos'
    else:
        return '8 ou mais anos'

df_improved2['faixa_idade_carro'] = df_improved2['idade_carro'].apply(faixa_idade_carro_range)


#clean 'Female' #error in data set
def clean_segurado_sexo(sexo):
    if sexo == 'female':
        return 'F'
    else:
        return sexo
    
df_improved2['segurado_sexo'] = df_improved2['segurado_sexo'].apply(clean_segurado_sexo)

#generate 'kit_gas'
def verifica_gnv(valor):
    if isinstance(valor, str) and 'gnv' in valor.lower(): 
        return 'Sim'
    else:
        return 'Não'

df_improved2['kit_gas'] = df_improved2['tipo_combustivel'].apply(verifica_gnv)

#generate 'faixa_clase_bonus'
def classe_bonus_range(valor):
    if valor == 0:
        return ' 0 '
    elif valor < 4:
        return '1 a 3'
    elif valor < 8:
        return '4 a 7'
    else:
        return '8 a 10'
    
df_improved2['faixa_clase_bonus'] = df_improved2['bonus_atual'].apply(classe_bonus_range)
 
#generate 'codigo_regiao'
def extrair_codigo_regiao(cep):
    cep_str = str(cep)  # Converter o valor para string
    if len(cep_str) == 8:
        return cep_str[:2]
    else:
        return cep_str[:1]


df_improved2['codigo_regiao'] = df_improved2['cep_circula'].apply(extrair_codigo_regiao)


#generate 'codigo_cidade'
def extrair_cidade(cep):
    cep_str = str(cep)  # Converter o valor para string
    if len(cep_str) == 8:
        return cep_str[:5]
    else:
        return cep_str[:4]


df_improved2['codigo_cidade'] = df_improved2['cep_circula'].apply(extrair_cidade)




#validate
df_improved2[['ano_modelo','idade_carro','faixa_idade_carro','tipo_combustivel','kit_gas','bonus_atual','faixa_clase_bonus', 'cep_circula', 'codigo_regiao','codigo_cidade', 'idade', 'faixa_idade']].head(5)

C:\Users\JOSE\AppData\Local\Temp\ipykernel_18908\784239756.py:5: UserWarning:

Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.

,ano_modelo,idade_carro,faixa_idade_carro,tipo_combustivel,kit_gas,bonus_atual,faixa_clase_bonus,cep_circula,codigo_regiao,codigo_cidade,idade,faixa_idade
0,2020,3,"2 a 3,9 anos",FLEX,Não,5,4 a 7,38412252,38,38412,39.0,37 a 46
1,2020,3,"2 a 3,9 anos",FLEX,Não,5,4 a 7,38412252,38,38412,39.0,37 a 46
2,2020,3,"2 a 3,9 anos",FLEX,Não,5,4 a 7,38412252,38,38412,39.0,37 a 46
3,2020,3,"2 a 3,9 anos",FLEX,Não,5,4 a 7,38412252,38,38412,39.0,37 a 46
4,2020,3,"2 a 3,9 anos",FLEX,Não,5,4 a 7,38412252,38,38412,39.0,37 a 46

In [254]:
data_atual_carro = datetime.now().year
print(data_atual_carro)

2023

In [255]:
df_improved2 = df_improved.copy()
df_improved2['premio_bruto'] = df_improved['premio_bruto'].astype(str).str.replace(',', '.').astype(float)
df_improved2.head(2)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,assistencia_24h_sim,assistencias_total,idade,faixa_idade,idade_carro,faixa_idade_carro,kit_gas,faixa_clase_bonus,codigo_regiao,codigo_cidade
0,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535619,16830520,14688,7799,1392675,1,61,3,...,Sim,Sim,39.0,37 a 46,3,"2 a 3,9 anos",Não,4 a 7,38,38412
1,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535618,16830520,14688,7799,1392675,2,61,3,...,Sim,Sim,39.0,37 a 46,3,"2 a 3,9 anos",Não,4 a 7,38,38412

In [256]:
#generate 'premio_ajustado'
df_improved2['premio_ajustado'] = df_improved2['premio_bruto'] * (1 - (df_improved2['comissao_retorno'] / 100)) / (df_improved2['percentual_fipe_retorno'] / 100)

In [257]:
#filter new data frame
df_filtered2 = df_improved2.filter(items = ['id_cotacao',
                                 'grupo_calculo',
                                 'preco_id',
                                 'cobertura_id',
                                 'usuario_id',
                                 'corretora_id',
                                 'cliente_id',
                                 'ranking',
                                 'REFERENCIA',
                                 'tempo',
                                 'produto',
                                 'tiposeguro',
                                 'seguradora_renovacao',
                                 'renovacao_propria',
                                 'datacalculo',
                                 'datahoracalculo',
                                 'dataresultado',
                                 'inicio_vigencia',
                                 'termino_vigencia',
                                 'tipo_cobertura',
                                 'tipo_cobertura_retorno',
                                 'tipofranquia',
                                 'danos_materiais',
                                 'danos_corporais',
                                 'danos_morais',
                                 'morte',
                                 'invalidez',
                                 'despesas_extraordinarias',
                                 'coberturas_vidros',
                                 'coberturas_vidros_retorno',
                                 'coberturas_17a25anos',
                                 'cobertura_para_outro_condutor',
                                 'coberturas_assistencia',
                                 'coberturas_carroreserva',
                                 'carro_reserva_retorno',
                                 'perfil_carro_reserva',
                                 'assistencias_km',
                                 'assistencia_24h_retorno',
                                 'dias_carro_reserva',
                                 'segurado_sexo',
                                 'segurado_estadocivil',
                                 'segurado_data_nascimento',
                                 'segurado_cep',
                                 'condutor_data_habilitacao',
                                 'relacao_cliente_condutor',
                                 'profissao_condutor_principal',
                                 'condutor_tipo_de_residencia',
                                 'codigo_fipe',
                                 'ano_fab',
                                 'ano_modelo',
                                 'zero_km',
                                 'percentual_fipe_retorno',
                                 'marcas_tipo',
                                 'tipo_veiculo',
                                 'fabricante',
                                 'modelo',
                                 'categoria_anti_furto',
                                 'marca_anti_furto',
                                 'alienado',
                                 'chassi_remarcado',
                                 'valor_kit_gas',
                                 'veiculo_blindado',
                                 'valor_blindado',
                                 'isencao_fiscal',
                                 'veiculo_retorno',
                                 'bonus_atual',
                                 'bonus_anterior',
                                 'vitima_furto',
                                 'qtd_sinistros',
                                 'cep_pernoite',
                                 'cep_circula',
                                 'distancia_residencia_trabalho',
                                 'carros_residencia',
                                 'garagem_residencia',
                                 'garagem_trabalho',
                                 'garagem_estudo',
                                 'utilizacao_veiculo',
                                 'km_mensal',
                                 'reposicao_zero_km',
                                 'oficina_retorno',
                                 'status',
                                 'premio_bruto',
                                 'premio_liquido',
                                 'danos_corporais_premio',
                                 'danos_materiais_premio',
                                 'danos_morais_premio',
                                 'isencao_franquia',
                                 'franquia_retorno',
                                 'comissao_retorno',
                                 'premio_ajustado',
                                 'faixa_idade_carro',
                                 'tipo_combustivel',
                                 'idade_carro'
                                 'kit_gas',
                                 'faixa_clase_bonus', 
                                 'codigo_regiao',
                                 'codigo_cidade', 
                                 'faixa_idade',
                                 'date_diff',
                                 'assistencias_total',
                                 'kit_gas',
                                 'idade_carro'])
  

df_filtered2.head(5)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,faixa_idade_carro,tipo_combustivel,faixa_clase_bonus,codigo_regiao,codigo_cidade,faixa_idade,date_diff,assistencias_total,kit_gas,idade_carro
0,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535619,16830520,14688,7799,1392675,1,61,3,...,"2 a 3,9 anos",FLEX,4 a 7,38,38412,37 a 46,365.0,Sim,Não,3
1,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535618,16830520,14688,7799,1392675,2,61,3,...,"2 a 3,9 anos",FLEX,4 a 7,38,38412,37 a 46,365.0,Sim,Não,3
2,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535752,16830520,14688,7799,1392675,3,27,27,...,"2 a 3,9 anos",FLEX,4 a 7,38,38412,37 a 46,365.0,Sim,Não,3
3,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535661,16830520,14688,7799,1392675,4,18,7,...,"2 a 3,9 anos",FLEX,4 a 7,38,38412,37 a 46,365.0,Sim,Não,3
4,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535721,16830520,14688,7799,1392675,5,22,17,...,"2 a 3,9 anos",FLEX,4 a 7,38,38412,37 a 46,365.0,Sim,Não,3

In [258]:
print(df_filtered2.columns)

Index(['id_cotacao', 'grupo_calculo', 'preco_id', 'cobertura_id', 'usuario_id',
       'corretora_id', 'cliente_id', 'ranking', 'REFERENCIA', 'tempo',
       'produto', 'tiposeguro', 'seguradora_renovacao', 'renovacao_propria',
       'datacalculo', 'datahoracalculo', 'dataresultado', 'inicio_vigencia',
       'termino_vigencia', 'tipo_cobertura', 'tipo_cobertura_retorno',
       'tipofranquia', 'danos_materiais', 'danos_corporais', 'danos_morais',
       'morte', 'invalidez', 'despesas_extraordinarias', 'coberturas_vidros',
       'coberturas_vidros_retorno', 'coberturas_17a25anos',
       'cobertura_para_outro_condutor', 'coberturas_assistencia',
       'coberturas_carroreserva', 'carro_reserva_retorno',
       'perfil_carro_reserva', 'assistencias_km', 'assistencia_24h_retorno',
       'dias_carro_reserva', 'segurado_sexo', 'segurado_estadocivil',
       'segurado_data_nascimento', 'segurado_cep', 'condutor_data_habilitacao',
       'relacao_cliente_condutor', 'profissao_condutor_principal',
       'condutor_tipo_de_residencia', 'codigo_fipe', 'ano_fab', 'ano_modelo',
       'zero_km', 'percentual_fipe_retorno', 'marcas_tipo', 'tipo_veiculo',
       'fabricante', 'modelo', 'categoria_anti_furto', 'marca_anti_furto',
       'alienado', 'chassi_remarcado', 'valor_kit_gas', 'veiculo_blindado',
       'valor_blindado', 'isencao_fiscal', 'veiculo_retorno', 'bonus_atual',
       'bonus_anterior', 'vitima_furto', 'qtd_sinistros', 'cep_pernoite',
       'cep_circula', 'distancia_residencia_trabalho', 'carros_residencia',
       'garagem_residencia', 'garagem_trabalho', 'garagem_estudo',
       'utilizacao_veiculo', 'km_mensal', 'reposicao_zero_km',
       'oficina_retorno', 'status', 'premio_bruto', 'premio_liquido',
       'danos_corporais_premio', 'danos_materiais_premio',
       'danos_morais_premio', 'isencao_franquia', 'franquia_retorno',
       'comissao_retorno', 'premio_ajustado', 'faixa_idade_carro',
       'tipo_combustivel', 'faixa_clase_bonus', 'codigo_regiao',
       'codigo_cidade', 'faixa_idade', 'date_diff', 'assistencias_total',
       'kit_gas', 'idade_carro'],
      dtype='object')

In [259]:
# Sort the DataFrame by 'premio_ajustado' and 'referencia'
df_filtered2.sort_values(['premio_ajustado', 'REFERENCIA'], inplace=True)

# Drop duplicate rows based on 'referencia' and 'premio_ajustado'
df_filtered2.drop_duplicates(subset=['REFERENCIA', 'premio_ajustado'], keep='first', inplace=True)

In [260]:
df_filtered2.head()

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,faixa_idade_carro,tipo_combustivel,faixa_clase_bonus,codigo_regiao,codigo_cidade,faixa_idade,date_diff,assistencias_total,kit_gas,idade_carro
28329,18726933,0018726933-1664821369-8c0e4d5e709cafee,327431331,16825575,23095,11943,6799680,1,11,86,...,8 ou mais anos,FLEX,1 a 3,87,87025,67 a 76,365.0,Sim,Não,14
229304,18728451,0018728451-1664824017-e7d83cfe0a0ba9da,327465396,16827215,23095,11943,3332901,1,11,84,...,8 ou mais anos,FLEX,4 a 7,87,87600,77 +,365.0,Sim,Não,11
123643,18717720,0018717720-1664798590-6dab855046b723ef,327220502,16815729,15094,7955,6795143,1,61,3,...,"2 a 3,9 anos",GASOLINA,0,35,35660,47 a 56,365.0,Não,Não,2
153049,18718203,0018718203-1664800243-7d651eb7aa59a3b0,327231419,16816237,15094,7955,5552239,1,61,3,...,"2 a 3,9 anos",GASOLINA,0,35,35661,37 a 46,365.0,Não,Não,2
145027,18717986,0018717986-1664799523-55fb11a4e59a958c,327226756,16816013,15094,7955,6795143,1,61,3,...,"2 a 3,9 anos",GASOLINA,1 a 3,35,35660,47 a 56,365.0,Não,Não,2

In [261]:
# Creates a new categorical variable 'grupo' based on the unique values of 'id_cotacao'.
df_filtered2['grupo'] = df_filtered2.groupby('id_cotacao').ngroup()

# Creates a new categorical variable 'categoria' based on combinations of 'grupo', 'date_diff', 'tipo_cobertura_retorno', 'assistencias_total', and 'franquia_retorno'.
df_filtered2['categoria'] = df_filtered2.groupby(['date_diff', 'tipo_cobertura_retorno', 'assistencias_total', 'franquia_retorno']).ngroup()

#Creates a new categorical variable 'filtro' based on combinations of 'codigo_fipe', 'codigo_regiao', 'segurado_sexo', 'faixa_idade', 'kit_gas', 'veiculo_blindado', and 'faixa_clase_bonus'.
df_filtered2['filtro'] = df_filtered2.groupby(['codigo_fipe', 'codigo_regiao', 'segurado_sexo', 'faixa_idade','kit_gas', 'veiculo_blindado','faixa_clase_bonus']).ngroup()

# Filters the DataFrame to exclude rows where 'marcas_tipo' is equal to 'moto'.
df_filtered2_moto = df_filtered2[df_filtered2['marcas_tipo'] != 'moto']

# Filters the groups with fewer than 5 rows using the 'filter' method.
df_filtered2_filtrados = df_filtered2_moto.groupby(['grupo', 'categoria', 'filtro']).filter(lambda x: len(x) > 3)

# Groups the filtered DataFrame by 'filtro', 'grupo', and 'categoria' and calculates the median of 'premio_ajustado'.
resultados2 = df_filtered2_filtrados.groupby(['filtro', 'grupo', 'categoria']).agg({'premio_ajustado': ['mean']})

# Merges the results back into the original DataFrame.
df_filtered2_filtrados = df_filtered2_filtrados.merge(resultados2, on=['grupo', 'categoria'])

C:\Users\JOSE\AppData\Local\Temp\ipykernel_18908\174590991.py:20: FutureWarning:

merging between different levels is deprecated and will be removed in a future version. (1 levels on the left, 2 on the right)

In [262]:
df_filtered2_filtrados.head()

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,codigo_cidade,faixa_idade,date_diff,assistencias_total,kit_gas,idade_carro,grupo,categoria,filtro,"(premio_ajustado, mean)"
0,18722841,0018722841-1664811336-d7fa4e64b9386584,327339135,16821246,9461,4978,3148474,1,30,23,...,41900,37 a 46,365.0,Sim,Não,3,5858,21.0,10957.0,1061.58625
1,18722841,0018722841-1664811336-d7fa4e64b9386584,327339138,16821246,9461,4978,3148474,2,30,23,...,41900,37 a 46,365.0,Sim,Não,3,5858,21.0,10957.0,1061.58625
2,18722841,0018722841-1664811175-fd6fa18a0485255a,327338275,16821211,9461,4978,3148474,4,30,18,...,41900,37 a 46,365.0,Sim,Não,3,5858,21.0,10957.0,1061.58625
3,18722841,0018722841-1664811336-d7fa4e64b9386584,327339398,16821246,9461,4978,3148474,6,11,79,...,41900,37 a 46,365.0,Sim,Não,3,5858,21.0,10957.0,1061.58625
4,18722841,0018722841-1664811336-d7fa4e64b9386584,327339136,16821246,9461,4978,3148474,13,12,23,...,41900,37 a 46,365.0,Sim,Não,3,5858,21.0,10957.0,1061.58625

In [263]:
# Calculates the 'desv_da_mediana' for each row, which is the difference between 'premio_ajustado' and the median value for the group, divided by the median value.
df_filtered2_filtrados['desv_da_media'] = (df_filtered2_filtrados['premio_ajustado'] - df_filtered2_filtrados[('premio_ajustado', 'mean')]) / df_filtered2_filtrados[('premio_ajustado', 'mean')]

In [264]:
    # Creates a histogram with the DataFrame 'df_filtered2_filtrados'.
    # 'x' is the 'desv_da_mediana' column of the 'df_filtered2_filtrados' DataFrame.
    # 'probability' means that the height of each bar on the y-axis represents the probability density of the values within each bin, rather than the raw count of observations.

    # fig=px.histogram(df_filtered2_filtrados, x=df_filtered2_filtrados['desv_da_media'], histnorm='probability')
    # fig.show()

In [265]:
    # # Creates a histogram with the DataFrame 'df_filtered2_filtrados'.
    # # 'x' is the 'desv_da_mediana' column of the 'df_filtered2_filtrados' DataFrame.
    # # 'y' is the count of observations.

    # fig=px.histogram(df_filtered2_filtrados, x=df_filtered2_filtrados['desv_da_media'])
    # fig.show()

In [266]:
from scipy import stats

# Calculate the probability density function of the 'desv_da_mediana' column
pdf = df_filtered2_filtrados['desv_da_media'].apply(lambda x: stats.norm.pdf(x, df_filtered2_filtrados['desv_da_media'].mean(), df_filtered2_filtrados['desv_da_media'].std()))

# Normalize the probability density function to sum up to one
pdf_norm = pdf / pdf.sum()

# Add the normalized probability density function to the DataFrame
df_filtered2_filtrados['probabilidade'] = pdf_norm

In [267]:
# Calculate the sum of probabilities when desv_da_mediana is lower than -0.2
sum_prob = df_filtered2_filtrados.loc[df_filtered2_filtrados['desv_da_media'] < -0.20, 'probabilidade'].sum()

# Print the sum
print("Sum of probabilities when desv_da_media < -0.2: ", sum_prob)

Sum of probabilities when desv_da_media < -0.2:  0.18921994295617378

In [268]:
# Calculate the sum of probabilities when desv_da_mediana is greater than 0.2
sum_prob1 = df_filtered2_filtrados.loc[df_filtered2_filtrados['desv_da_media'] > 0.20, 'probabilidade'].sum()

# Print the sum
print("Sum of probabilities when desv_da_media > 0.2: ", sum_prob1)

Sum of probabilities when desv_da_media > 0.2:  0.14342708722429431

In [269]:

# Assume that df_filtered2_filtrados is already defined

# Creates a new column 'seguradora' in the filtered DataFrame 'df_filtered2_filtrados', which is set to the values in the 'REFERENCIA' column.
df_filtered2_filtrados['seguradora'] = df_filtered2_filtrados['REFERENCIA']

# Groups by the 'seguradora'
por_seguradora = df_filtered2_filtrados.groupby('seguradora')

# # Create a list of colors to use for each seguradora
# colors = px.colors.qualitative.Plotly

# # Create a new figure object
# fig = go.Figure()

# # Loop over each seguradora and corresponding data in the grouped DataFrame using a for loop.
# for i, (seguradora, dados) in enumerate(por_seguradora):

#     # Add a histogram trace for the current seguradora
#     fig.add_trace(
#         go.Histogram(
#             x=dados['desv_da_media'],
#             histnorm='probability',
#             name=seguradora,
#             opacity=0.5,
#             marker=dict(line=dict(width=1, color=colors[i % len(colors)]))
#         )
#     )

# # Update the layout to show the histograms overlaid on top of each other
# fig.update_layout(barmode='overlay')

# # Set the axis labels and plot title
# fig.update_xaxes(title_text='desv_da_media')
# fig.update_yaxes(title_text='Probability')
# fig.update_layout(title='Histograms of desv_da_media by Seguradora')

# # Show the figure
# fig.show()

In [270]:
# # Loops over each seguradora and corresponding data in the grouped DataFrame using a for loop.
# for seguradora, dados in por_seguradora: 

#     # Creates a histogram for 'desv_da_mediana'
#     fig=px.histogram(dados, x=dados['desv_da_media'], histnorm='probability')
#     fig.update_layout(title = (seguradora))
#     fig.show()

In [271]:
# # Group by 'seguradora'
# por_seguradora = df_filtered2_filtrados.groupby('seguradora')

# #Loops over each seguradora 
# for seguradora, dados in por_seguradora:
 
#     # Calculate the probability density function of the 'desv_da_mediana' column for the current 'seguradora'
#     pdf = dados['desv_da_media'].apply(lambda x: stats.norm.pdf(x, dados['desv_da_media'].mean(), dados['desv_da_media'].std()))

#     # Normalize the probability density function to sum up to one
#     pdf_norm = pdf / pdf.sum()

#     # Add the normalized probability density function to the current 'seguradora' group
#     dados['probabilidade_seg'] = pdf_norm

#     # Filter the data where 'desv_da_mediana' is less than -0.2 and stores the sum of the 'probabilidade_seg' column in 'sum_prob3'.
#     sum_prob3 = dados.loc[dados['desv_da_media'] < -0.2, 'probabilidade_seg'].sum()

#     # Print the result
#     print(f"Seguradora {seguradora}: Sum of probabilities when desv_da_media < -0.2: {sum_prob3}")

In [272]:
# # Group by 'seguradora'
# por_seguradora = df_filtered2_filtrados.groupby('seguradora')

# # Calculate the probability density function for each 'seguradora'
# for seguradora, dados in por_seguradora:
    
#     # Calculate the probability density function of the 'desv_da_mediana' column for the current 'seguradora'
#     pdf = dados['desv_da_media'].apply(lambda x: stats.norm.pdf(x, dados['desv_da_media'].mean(), dados['desv_da_media'].std()))

#     # Normalize the probability density function to sum up to one
#     pdf_norm = pdf / pdf.sum()

#     # Add the normalized probability density function to the current 'seguradora' group
#     dados['probabilidade_seg'] = pdf_norm

# # Filter the data where 'desv_da_mediana' is more than 0.2 and stores the sum of the 'probabilidade_seg' column in 'sum_prob3'.
#     sum_prob3 = dados.loc[dados['desv_da_media'] > 0.2, 'probabilidade_seg'].sum()

#     # Print the result
#     print(f"Seguradora {seguradora}: Sum of probabilities when desv_da_media > 0.2: {sum_prob3}")

In [273]:
# %matplotlib inline

# # Creates a new column 'seguradora' in the filtered DataFrame 'df_filtered2_filtrados', which is set to the values in the 'REFERENCIA' column.
# df_filtered2_filtrados['seguradora'] = df_filtered2_filtrados['REFERENCIA']

# # Groups  by the 'seguradora' 
# por_seguradora = df_filtered2_filtrados.groupby('seguradora')

# # Loops over each seguradora and corresponding data in the grouped DataFrame using a for loop.
# for seguradora, dados in por_seguradora: 
    
#     # Creates a histogram for 'desv_da_mediana'
#     fig=px.histogram(dados, x=dados['desv_da_media'])
#     fig.update_layout(title = (seguradora))
#     fig.show()

In [274]:
df_filtered2_filtrados['preco_caro'] = np.where(df_filtered2_filtrados['premio_ajustado'] > np.percentile(df_filtered2_filtrados['premio_ajustado'], 75) , 1, 0)
df_filtered2_filtrados['preco_barato'] = np.where(df_filtered2_filtrados['premio_ajustado'] < np.percentile(df_filtered2_filtrados['premio_ajustado'], 25) , 1, 0)
df_filtered2_filtrados['preco_normal'] = np.where((df_filtered2_filtrados['premio_ajustado'] <= np.percentile(df_filtered2_filtrados['premio_ajustado'], 75)) & (df_filtered2_filtrados['premio_ajustado'] >= np.percentile(df_filtered2_filtrados['premio_ajustado'], 25)), 1, 0)

In [275]:
df_filtered2_filtrados.head(3)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,grupo,categoria,filtro,"(premio_ajustado, mean)",desv_da_media,probabilidade,seguradora,preco_caro,preco_barato,preco_normal
0,18722841,0018722841-1664811336-d7fa4e64b9386584,327339135,16821246,9461,4978,3148474,1,30,23,...,5858,21.0,10957.0,1061.58625,-0.701639,8.644866e-07,30,0,1,0
1,18722841,0018722841-1664811336-d7fa4e64b9386584,327339138,16821246,9461,4978,3148474,2,30,23,...,5858,21.0,10957.0,1061.58625,-0.652181,1.191146e-06,30,0,1,0
2,18722841,0018722841-1664811175-fd6fa18a0485255a,327338275,16821211,9461,4978,3148474,4,30,18,...,5858,21.0,10957.0,1061.58625,-0.003143,9.124981e-06,30,0,1,0

In [276]:
# %matplotlib inline


# # Define the variables to plot
# var_preco = ['fabricante', 'codigo_regiao', 'segurado_sexo', 'faixa_idade', 'faixa_clase_bonus']

# # Define the colors for each price category
# colors = {'preco_barato': 'green', 'preco_normal': 'blue', 'preco_caro': 'red'}

# # Loop over each variable to plot
# for var in var_preco:

#     # Group the data by seguradora and price category
#     por_seguradora_filtro = df_filtered2_filtrados.groupby(['seguradora'])

#     # Loop over each seguradora and corresponding data in the grouped DataFrame using a for loop
#     for seguradora, dados in por_seguradora_filtro:

#         # Create a histogram for the current variable and seguradora
#         fig = px.histogram(
#             dados,
#             x=var,
#             y=['preco_barato', 'preco_normal', 'preco_caro'],
#             histnorm='probability',
#             barmode='group',
#             color_discrete_map=colors,
#             opacity=0.5
#         )

#         # Update the plot title
#         fig.update_layout(title=var + str(seguradora))

#         # Show the plot
#         fig.show()

In [277]:
'preco_barato' in df_filtered2_filtrados.columns

True

In [278]:

# group by 'filtro', 'grupo', and 'categoria' and calculate median and count of 'premio_ajustado'
df_filtered3_filtrados = df_filtered2_filtrados.sort_values('premio_ajustado').groupby(['grupo', 'categoria','filtro']).nth([0,1])

# Filtrar os grupos com moto
df_filtered3_filtrados = df_filtered3_filtrados.groupby(['grupo', 'categoria']).filter(lambda x: len(x) > 1)

# group by 'filtro', 'grupo', and 'categoria' and calculate min, max, and standard deviation of 'premio_ajustado'
resultados3 = df_filtered3_filtrados.groupby(['filtro', 'grupo', 'categoria']).agg({'premio_ajustado': ['min', 'max']})

# merge the results back into the original DataFrame
df_filtered3_filtrados = df_filtered3_filtrados.merge(resultados3, on=['grupo', 'categoria'])

df_filtered3_filtrados.head(4)

C:\Users\JOSE\AppData\Local\Temp\ipykernel_18908\1292417620.py:11: FutureWarning:

merging between different levels is deprecated and will be removed in a future version. (1 levels on the left, 2 on the right)

                 id_cotacao                           grupo_calculo  \
grupo categoria
0     15.0         13296967  0013296967-1664831874-5127bd118ec1b3f9
      15.0         13296967  0013296967-1664831874-5127bd118ec1b3f9
1     9.0          15642675  0015642675-1664808668-d4864d0f8a8eb584
      9.0          15642675  0015642675-1664808668-d4864d0f8a8eb584

                  preco_id  cobertura_id  usuario_id  corretora_id  \
grupo categoria
0     15.0       327535618      16830520       14688          7799
      15.0       327535661      16830520       14688          7799
1     9.0        327321373      16820418       22777         11747
      9.0        327321397      16820418       22777         11747

                 cliente_id  ranking  REFERENCIA  tempo  ... idade_carro  \
grupo categoria                                          ...
0     15.0          1392675        2          61      3  ...           3
      15.0          1392675        4          18      7  ...           3
1     9.0           4457300       12          16     15  ...           2
      9.0           4457300       18          27     17  ...           2

                (premio_ajustado, mean) desv_da_media probabilidade  \
grupo categoria
0     15.0                  6340.062029     -0.566997      0.000002
      15.0                  6340.062029     -0.180473      0.000008
1     9.0                   4817.139750     -0.512430      0.000003
      9.0                   4817.139750     -0.313410      0.000006

                seguradora preco_caro preco_barato preco_normal  \
grupo categoria
0     15.0              61          0            0            1
      15.0              18          0            0            1
1     9.0               16          0            0            1
      9.0               27          0            0            1

                (premio_ajustado, min) (premio_ajustado, max)
grupo categoria
0     15.0                 2745.267368              5195.8545
      15.0                 2745.267368              5195.8545
1     9.0                  2348.694000              3307.4010
      9.0                  2348.694000              3307.4010

[4 rows x 109 columns]

In [279]:
# Calculate 'dist_min' for each row
df_filtered3_filtrados['dist_min'] = (abs(df_filtered3_filtrados[('premio_ajustado')] - df_filtered3_filtrados[('premio_ajustado', 'max')])) / df_filtered3_filtrados[('premio_ajustado', 'max')]

In [280]:
# Filter the DataFrame to only include rows where 'premio_ajustado' is equal to 'min'
df_filtered3_filtrados_min = df_filtered3_filtrados.loc[df_filtered3_filtrados[('premio_ajustado')] == df_filtered3_filtrados[('premio_ajustado', 'min')]]
df_filtered3_filtrados_min ['desv_med'] = abs(df_filtered3_filtrados_min['desv_da_media'])

C:\Users\JOSE\AppData\Local\Temp\ipykernel_18908\3929291423.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [281]:
df_filtered3_filtrados_min.head(4)

                 id_cotacao                           grupo_calculo  \
grupo categoria
0     15.0         13296967  0013296967-1664831874-5127bd118ec1b3f9
1     9.0          15642675  0015642675-1664808668-d4864d0f8a8eb584
      15.0         15642675  0015642675-1664808668-d4864d0f8a8eb584
4     15.0         15676699  0015676699-1664815311-e8392778410edeea

                  preco_id  cobertura_id  usuario_id  corretora_id  \
grupo categoria
0     15.0       327535618      16830520       14688          7799
1     9.0        327321373      16820418       22777         11747
      15.0       327321199      16820418       22777         11747
4     15.0       327360655      13554483        9490          4992

                 cliente_id  ranking  REFERENCIA  tempo  ... desv_da_media  \
grupo categoria                                          ...
0     15.0          1392675        2          61      3  ...     -0.566997
1     9.0           4457300       12          16     15  ...     -0.512430
      15.0          4457300        3          61      3  ...     -0.590656
4     15.0           843197        3          30     17  ...     -0.358735

                probabilidade seguradora preco_caro preco_barato preco_normal  \
grupo categoria
0     15.0           0.000002         61          0            0            1
1     9.0            0.000003         16          0            0            1
      15.0           0.000002         61          0            1            0
4     15.0           0.000005         30          0            1            0

                (premio_ajustado, min) (premio_ajustado, max)  dist_min  \
grupo categoria
0     15.0                 2745.267368              5195.8545  0.471643
1     9.0                  2348.694000              3307.4010  0.289867
      15.0                 1276.335000              1804.8690  0.292838
4     15.0                  913.113000               948.2600  0.037065

                 desv_med
grupo categoria
0     15.0       0.566997
1     9.0        0.512430
      15.0       0.590656
4     15.0       0.358735

[4 rows x 111 columns]

In [282]:
# # define 'seguradora' as 'REFERENCIA'
# df_filtered3_filtrados_min['seguradora'] = df_filtered3_filtrados_min['REFERENCIA']
# # agrupar por seguradora
# por_seguradora2 = df_filtered3_filtrados_min.groupby('seguradora')

# for seguradora, grouped_df in por_seguradora2:
#     fig = px.scatter(grouped_df, x='desv_med', y='dist_min')
#     fig.update_layout(title=str(seguradora))
#     fig.show()

In [283]:
df_filtered3_filtrados_min.head(5)

                 id_cotacao                           grupo_calculo  \
grupo categoria
0     15.0         13296967  0013296967-1664831874-5127bd118ec1b3f9
1     9.0          15642675  0015642675-1664808668-d4864d0f8a8eb584
      15.0         15642675  0015642675-1664808668-d4864d0f8a8eb584
4     15.0         15676699  0015676699-1664815311-e8392778410edeea
6     15.0         15721545  0015721545-1664817441-cc2b8a83d78fb0e3

                  preco_id  cobertura_id  usuario_id  corretora_id  \
grupo categoria
0     15.0       327535618      16830520       14688          7799
1     9.0        327321373      16820418       22777         11747
      15.0       327321199      16820418       22777         11747
4     15.0       327360655      13554483        9490          4992
6     15.0       327380142      16823218       16364          8421

                 cliente_id  ranking  REFERENCIA  tempo  ... desv_da_media  \
grupo categoria                                          ...
0     15.0          1392675        2          61      3  ...     -0.566997
1     9.0           4457300       12          16     15  ...     -0.512430
      15.0          4457300        3          61      3  ...     -0.590656
4     15.0           843197        3          30     17  ...     -0.358735
6     15.0          2169849        2          20     12  ...     -0.291334

                probabilidade seguradora preco_caro preco_barato preco_normal  \
grupo categoria
0     15.0           0.000002         61          0            0            1
1     9.0            0.000003         16          0            0            1
      15.0           0.000002         61          0            1            0
4     15.0           0.000005         30          0            1            0
6     15.0           0.000006         20          0            0            1

                (premio_ajustado, min) (premio_ajustado, max)  dist_min  \
grupo categoria
0     15.0                 2745.267368              5195.8545  0.471643
1     9.0                  2348.694000              3307.4010  0.289867
      15.0                 1276.335000              1804.8690  0.292838
4     15.0                  913.113000               948.2600  0.037065
6     15.0                 3836.470000              3975.1900  0.034896

                 desv_med
grupo categoria
0     15.0       0.566997
1     9.0        0.512430
      15.0       0.590656
4     15.0       0.358735
6     15.0       0.291334

[5 rows x 111 columns]

In [284]:
# Group df_filtered3_filtrados_min by 'seguradora'
df_filtered3_filtrados_min_grouped = df_filtered3_filtrados_min.groupby('seguradora')

# Loop over each 'seguradora'
for seguradora, dados in df_filtered3_filtrados_min_grouped:

    # Calculate the percentage of 'premio_ajustado' values in the filtered DataFrame for the current 'seguradora' that have a 'dist_min' > 0.2
    perc_dist_min1 = (dados['dist_min'] > 0.2).mean() * 100
    
    # Print the result
    print(f"Seguradora {seguradora}: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: {perc_dist_min1:.2f}%")

Seguradora 11: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 0.36%
Seguradora 12: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 17.07%
Seguradora 13: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 34.09%
Seguradora 15: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 31.67%
Seguradora 16: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 21.29%
Seguradora 18: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 31.43%
Seguradora 20: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 0.00%
Seguradora 22: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 25.61%
Seguradora 24: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 20.95%
Seguradora 25: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 20.63%
Seguradora 26: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 31.76%
Seguradora 27: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 14.63%
Seguradora 30: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 43.56%
Seguradora 32: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 15.24%
Seguradora 60: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 42.31%
Seguradora 61: Percentage of 'premio_ajustado' values in df_filtered3_filtrados_min for this 'seguradora' that have a 'dist_min' > 0.2: 54.20%

In [285]:
# Define a function to check if the difference between two values is less than 0.1
def is_within_tolerance(a, b, tolerance=0.2):
    return abs((a - b)/b) <= tolerance

# Group the dataframe by 'filtro', 'grupo', 'categoria', and then loop through the groups
for group_name, group_df in df_filtered2_filtrados.groupby(['filtro', 'grupo', 'categoria']):
    # Get the unique values of 'premio_ajustado' in the group
    unique_premios = group_df['premio_ajustado'].unique()
    
    # If there is only one unique value, set the 'preco_validado' column to 'nao_validado'
    if len(unique_premios) == 1:
        group_df['preco_validado'] = 'nao_validado'
    else:
        # Otherwise, loop through the rows in the group and compare 'premio_ajustado' to the other values
        for idx, row in group_df.iterrows():
            other_premios = [p for p in unique_premios if p != row['premio_ajustado']]
            within_tolerance = [is_within_tolerance(row['premio_ajustado'], p) for p in other_premios]
            
            # If the difference between 'premio_ajustado' and any other value is less than 0.1,
            # check if they are from different 'seguradora' groups, and set 'preco_validado' to 'validado'
            if any(within_tolerance):
                other_seguradoras = [s for s in group_df['seguradora'].unique() if s != row['seguradora']]
                same_seguradora = [s for s in other_seguradoras if str(s).startswith(str(row['seguradora']))]
                if len(same_seguradora) == 0:
                    group_df.at[idx, 'preco_validado'] = 'validado'
                else:
                    group_df.at[idx, 'preco_validado'] = 'duplicado'
            else:
                # Otherwise, set 'preco_validado' to 'nao_validado'
                group_df.at[idx, 'preco_validado'] = 'nao_validado'

    
    # Update the group in the original dataframe with the new 'preco_validado' values
    df_filtered2_filtrados.loc[group_df.index, 'preco_validado'] = group_df['preco_validado']

In [286]:
df_filtered2_filtrados[df_filtered2_filtrados['preco_validado'] != 'duplicado'].head(20)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,categoria,filtro,"(premio_ajustado, mean)",desv_da_media,probabilidade,seguradora,preco_caro,preco_barato,preco_normal,preco_validado
0,18722841,0018722841-1664811336-d7fa4e64b9386584,327339135,16821246,9461,4978,3148474,1,30,23,...,21.0,10957.0,1061.586250,-0.701639,8.644866e-07,30,0,1,0,validado
1,18722841,0018722841-1664811336-d7fa4e64b9386584,327339138,16821246,9461,4978,3148474,2,30,23,...,21.0,10957.0,1061.586250,-0.652181,1.191146e-06,30,0,1,0,validado
2,18722841,0018722841-1664811175-fd6fa18a0485255a,327338275,16821211,9461,4978,3148474,4,30,18,...,21.0,10957.0,1061.586250,-0.003143,9.124981e-06,30,0,1,0,validado
3,18722841,0018722841-1664811336-d7fa4e64b9386584,327339398,16821246,9461,4978,3148474,6,11,79,...,21.0,10957.0,1061.586250,0.081698,8.838446e-06,11,0,1,0,validado
4,18722841,0018722841-1664811336-d7fa4e64b9386584,327339136,16821246,9461,4978,3148474,13,12,23,...,21.0,10957.0,1061.586250,0.631971,1.348712e-06,12,0,1,0,validado
5,18722841,0018722841-1664811336-d7fa4e64b9386584,327339139,16821246,9461,4978,3148474,14,26,23,...,21.0,10957.0,1061.586250,0.643293,1.258641e-06,26,0,1,0,validado
6,18723317,0018723317-1664827240-7151d93dbd25ac5e,327499951,16828885,25878,14376,1198258,1,30,18,...,25.0,3741.0,1149.244200,-0.684820,9.665854e-07,30,0,1,0,nao_validado
7,18723317,0018723317-1664827240-7151d93dbd25ac5e,327499922,16828885,25878,14376,1198258,5,22,16,...,25.0,3741.0,1149.244200,-0.368649,4.761139e-06,22,0,1,0,validado
8,18723317,0018723317-1664827240-7151d93dbd25ac5e,327499954,16828885,25878,14376,1198258,6,26,18,...,25.0,3741.0,1149.244200,-0.258616,6.625271e-06,26,0,1,0,validado
9,18723317,0018723317-1664827240-7151d93dbd25ac5e,327499805,16828885,25878,14376,1198258,12,18,7,...,25.0,3741.0,1149.244200,0.210079,7.387523e-06,18,0,1,0,nao_validado
10,18723317,0018723317-1664827240-7151d93dbd25ac5e,327500343,16828885,25878,14376,1198258,36,11,56,...,25.0,3741.0,1149.244200,1.102005,2.725628e-08,11,0,0,1,nao_validado
11,18720972,0018720972-1664806674-9a8b1c2efb9c5544,327299407,16819375,35474,19367,6596272,1,30,27,...,21.0,1158.0,2285.449143,-0.832653,3.302558e-07,30,0,1,0,nao_validado
12,18720972,0018720972-1664806674-9a8b1c2efb9c5544,327299406,16819375,35474,19367,6596272,2,30,27,...,21.0,1158.0,2285.449143,-0.732818,6.978743e-07,30,0,1,0,nao_validado
13,18720972,0018720972-1664806674-9a8b1c2efb9c5544,327299218,16819375,35474,19367,6596272,3,18,7,...,21.0,1158.0,2285.449143,-0.284128,6.200344e-06,18,0,1,0,nao_validado
14,18720972,0018720972-1664806342-f0340a4b22a9291c,327295576,16819193,35474,19367,6596272,8,30,26,...,21.0,1158.0,2285.449143,-0.047333,9.028065e-06,30,0,1,0,nao_validado
15,18720972,0018720972-1664806674-9a8b1c2efb9c5544,327299409,16819375,35474,19367,6596272,12,26,27,...,21.0,1158.0,2285.449143,0.254441,6.693560e-06,26,0,0,1,nao_validado
16,18720972,0018720972-1664806674-9a8b1c2efb9c5544,327299648,16819375,35474,19367,6596272,22,12,47,...,21.0,1158.0,2285.449143,0.577143,1.852445e-06,12,0,0,1,nao_validado
17,18720972,0018720972-1664806674-9a8b1c2efb9c5544,327299439,16819375,35474,19367,6596272,40,24,30,...,21.0,1158.0,2285.449143,1.065348,3.986951e-08,24,0,0,1,nao_validado
18,18722938,0018722938-1664811664-dad74cfcd378ef9a,327340664,16821320,10435,5533,6801148,1,30,25,...,14.0,7399.0,1680.885952,-0.757909,5.834624e-07,30,0,1,0,nao_validado
19,18722938,0018722938-1664811664-dad74cfcd378ef9a,327340675,16821320,10435,5533,6801148,15,12,25,...,14.0,7399.0,1680.885952,-0.211586,7.365081e-06,12,0,1,0,validado

In [287]:
df_filtered2_filtrados.head(5)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,categoria,filtro,"(premio_ajustado, mean)",desv_da_media,probabilidade,seguradora,preco_caro,preco_barato,preco_normal,preco_validado
0,18722841,0018722841-1664811336-d7fa4e64b9386584,327339135,16821246,9461,4978,3148474,1,30,23,...,21.0,10957.0,1061.58625,-0.701639,8.644866e-07,30,0,1,0,validado
1,18722841,0018722841-1664811336-d7fa4e64b9386584,327339138,16821246,9461,4978,3148474,2,30,23,...,21.0,10957.0,1061.58625,-0.652181,1.191146e-06,30,0,1,0,validado
2,18722841,0018722841-1664811175-fd6fa18a0485255a,327338275,16821211,9461,4978,3148474,4,30,18,...,21.0,10957.0,1061.58625,-0.003143,9.124981e-06,30,0,1,0,validado
3,18722841,0018722841-1664811336-d7fa4e64b9386584,327339398,16821246,9461,4978,3148474,6,11,79,...,21.0,10957.0,1061.58625,0.081698,8.838446e-06,11,0,1,0,validado
4,18722841,0018722841-1664811336-d7fa4e64b9386584,327339136,16821246,9461,4978,3148474,13,12,23,...,21.0,10957.0,1061.58625,0.631971,1.348712e-06,12,0,1,0,validado

In [288]:
#Mergeando os 2
df_filtered4_filtrados = pd.merge(df_filtered3_filtrados, df_filtered2_filtrados[['preco_id', 'preco_validado']], on=['preco_id'], how='left')
df_filtered4_filtrados.head(5)

,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,REFERENCIA,tempo,...,desv_da_media,probabilidade,seguradora,preco_caro,preco_barato,preco_normal,"(premio_ajustado, min)","(premio_ajustado, max)",dist_min,preco_validado
0,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535618,16830520,14688,7799,1392675,2,61,3,...,-0.566997,0.000002,61,0,0,1,2745.267368,5195.8545,0.471643,nao_validado
1,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535661,16830520,14688,7799,1392675,4,18,7,...,-0.180473,0.000008,18,0,0,1,2745.267368,5195.8545,0.000000,validado
2,15642675,0015642675-1664808668-d4864d0f8a8eb584,327321373,16820418,22777,11747,4457300,12,16,15,...,-0.512430,0.000003,16,0,0,1,2348.694000,3307.4010,0.289867,nao_validado
3,15642675,0015642675-1664808668-d4864d0f8a8eb584,327321397,16820418,22777,11747,4457300,18,27,17,...,-0.313410,0.000006,27,0,0,1,2348.694000,3307.4010,0.000000,nao_validado
4,15642675,0015642675-1664808668-d4864d0f8a8eb584,327321199,16820418,22777,11747,4457300,3,61,3,...,-0.590656,0.000002,61,0,1,0,1276.335000,1804.8690,0.292838,nao_validado

In [289]:
duplicatas = df_filtered4_filtrados.columns.duplicated()
colunas_duplicadas = df_filtered4_filtrados.columns[duplicatas]

if len(colunas_duplicadas) > 0:
    print("As seguintes colunas estão duplicadas:")
    print(colunas_duplicadas)
else:
    print("Não há colunas duplicadas no DataFrame.")

Não há colunas duplicadas no DataFrame.

In [306]:
print(df_filtered4_filtrados['assistencias_total'])

0        Sim
1        Sim
2        Sim
3        Sim
4        Sim
        ...
29707    Sim
29708    Sim
29709    Sim
29710    Sim
29711    Sim
Name: assistencias_total, Length: 29712, dtype: object

In [290]:
print(df_filtered4_filtrados['idade_carro'])

0         3
1         3
2         2
3         2
4         2
         ..
29707     6
29708    20
29709    20
29710     5
29711     5
Name: idade_carro, Length: 29712, dtype: int32

In [291]:
df_filtered4_filtrados.to_csv('SegfyDF6.csv',index=False)

In [292]:
# import plotly.graph_objects as go

# # Define the colors for each histogram
# colors = {'validado': 'green', 'all_data': 'blue', 'nao_validado': 'red'}

# # Create a new figure object
# fig = go.Figure()

# # Add the histograms for the 'validado' data as a separate trace
# validado_data = df_filtered2_filtrados[df_filtered2_filtrados['preco_validado'] == 'validado']
# fig.add_trace(
#     go.Histogram(
#         x=validado_data['desv_da_media'],
#         name='Validated',
#         marker_color=colors['validado'],
#         opacity=0.4,
#         marker=dict(line=dict(width=0))
#     )
# )

# # Add the histograms for the 'nao_validado' data as a separate trace
# nao_validado_data = df_filtered2_filtrados[df_filtered2_filtrados['preco_validado'] == 'nao_validado']
# fig.add_trace(
#     go.Histogram(
#         x=nao_validado_data['desv_da_media'],
#         name='Not Validated',
#         marker_color=colors['nao_validado'],
#         opacity=0.4,
#         marker=dict(line=dict(width=0))
#     )
# )

# # Add the histogram for all data as a separate trace
# fig.add_trace(
#     go.Histogram(
#         x=df_filtered2_filtrados['desv_da_media'],
#         name='All Data',
#         marker_color=colors['all_data'],
#         opacity=0.4,
#         marker=dict(line=dict(width=0))
#     )
# )

# # Update the layout to show the histograms overlaid on top of each other
# fig.update_layout(barmode='overlay')

# # Set the axis labels and plot title
# fig.update_xaxes(title_text='desv_da_media')
# fig.update_yaxes(title_text='Probability')
# fig.update_layout(title='Histograms of desv_da_media by Preco Validado')

# # Show the figure
# fig.show()

In [293]:
# Calculate the median and standard deviation for the 'validado' data
validado_data = df_filtered2_filtrados[df_filtered2_filtrados['preco_validado'] == 'validado']['desv_da_media']
validado_median = np.median(validado_data)
validado_std = np.std(validado_data)

# Calculate the median and standard deviation for the 'nao_validado' data
nao_validado_data = df_filtered2_filtrados[df_filtered2_filtrados['preco_validado'] == 'nao_validado']['desv_da_media']
nao_validado_median = np.median(nao_validado_data)
nao_validado_std = np.std(nao_validado_data)

# Calculate the median and standard deviation for all data
all_data_median = np.median(df_filtered2_filtrados['desv_da_media'])
all_data_std = np.std(df_filtered2_filtrados['desv_da_media'])

# Print the results
print('Validado median: {:.2f}, standard deviation: {:.2f}'.format(validado_median, validado_std))
print('Nao Validado median: {:.2f}, standard deviation: {:.2f}'.format(nao_validado_median, nao_validado_std))
print('All Data median: {:.2f}, standard deviation: {:.2f}'.format(all_data_median, all_data_std))

Validado median: -0.02, standard deviation: 0.27
Nao Validado median: -0.21, standard deviation: 0.62
All Data median: -0.02, standard deviation: 0.32

In [294]:
# %matplotlib inline


# # Creates a new column 'seguradora' in the filtered DataFrame 'df_filtered2_filtrados', which is set to the values in the 'REFERENCIA' column.
# df_filtered2_filtrados['seguradora'] = df_filtered2_filtrados['REFERENCIA']

# # Groups by the 'seguradora'
# por_seguradora = df_filtered2_filtrados.groupby('seguradora')

# # Loops over each seguradora and corresponding data in the grouped DataFrame using a for loop.
# for seguradora, dados in por_seguradora:

#     # Define the colors for each histogram
#     colors = {'validado': 'green', 'all_data': 'blue', 'nao_validado': 'red'}

#     # Create a new figure object
#     fig = go.Figure()

#     # Add the histograms for the 'validado' data as a separate trace
#     validado_data = dados[dados['preco_validado'] == 'validado']
#     fig.add_trace(
#         go.Histogram(
#             x=validado_data['desv_da_media'],
#             name='Validated',
#             marker_color=colors['validado'],
#             opacity=0.6,
#             marker=dict(line=dict(width=0))
#         )
#     )

#     # Add the histograms for the 'nao_validado' data as a separate trace
#     nao_validado_data = dados[dados['preco_validado'] == 'nao_validado']
#     fig.add_trace(
#         go.Histogram(
#             x=nao_validado_data['desv_da_media'],
#             name='Not Validated',
#             marker_color=colors['nao_validado'],
#             opacity=0.2,
#             marker=dict(line=dict(width=0))
#         )
#     )

#     # Add the histogram for all data as a separate trace
#     fig.add_trace(
#         go.Histogram(
#             x=dados['desv_da_media'],
#             name='All Data',
#             marker_color=colors['all_data'],
#             opacity=0.3,
#             marker=dict(line=dict(width=0))
#         )
#     )

#     # Update the layout to show the histograms overlaid on top of each other
#     fig.update_layout(barmode='overlay')

#     # Set the axis labels and plot title
#     fig.update_xaxes(title_text='desv_da_media')
#     fig.update_yaxes(title_text='Count')
#     fig.update_layout(title='Histograms of desv_da_media by Preco Validado' + str(seguradora))

#     # Show the figure
#     fig.show()

In [295]:
validados_count = len(df_filtered2_filtrados[df_filtered2_filtrados['preco_validado'] == 'validado'])
print(f"Number of 'validado' rows in 'df_filtered2_filtrados': {validados_count}")

Number of 'validado' rows in 'df_filtered2_filtrados': 134118

In [296]:
print(len(df_filtered2_filtrados))

148360

In [297]:
# Group the data by 'seguradora' and 'preco_validado'
precos_seguradora_validados = df_filtered2_filtrados.groupby(['seguradora', 'preco_validado'])

validados_size = precos_seguradora_validados.size()

# Group the data by 'seguradora' 
numeros_precos_seguradora = df_filtered2_filtrados.groupby(['seguradora'])

precos_size = numeros_precos_seguradora.size()

# Calculate the percentage of 'preco_ajustado' that is 'validated' for each 'seguradora'
validated_pct_by_seguradora = (validados_size / precos_size) * 100

# Print the results
print(validated_pct_by_seguradora)

seguradora  preco_validado
11          nao_validado       0.165044
            validado          99.834956
12          nao_validado       1.653097
            validado          98.346903
13          nao_validado       6.777232
            validado          93.222768
15          nao_validado      23.244147
            validado          76.755853
16          nao_validado      18.521527
            validado          81.478473
18          nao_validado      18.808676
            validado          81.191324
20          nao_validado       0.017543
            validado          99.982457
22          nao_validado      12.081129
            validado          87.918871
24          nao_validado      19.519095
            validado          80.480905
25          nao_validado      10.728911
            validado          89.271089
26          nao_validado      16.678563
            validado          83.321437
27          nao_validado      12.635379
            validado          87.364621
30          nao_validado      12.323907
            validado          87.676093
32          nao_validado       3.490049
            validado          96.509951
60          nao_validado      18.464730
            validado          81.535270
61          nao_validado      29.309313
            validado          70.690687
dtype: float64

In [298]:
df_filtered3_filtrados_min.head()

                 id_cotacao                           grupo_calculo  \
grupo categoria
0     15.0         13296967  0013296967-1664831874-5127bd118ec1b3f9
1     9.0          15642675  0015642675-1664808668-d4864d0f8a8eb584
      15.0         15642675  0015642675-1664808668-d4864d0f8a8eb584
4     15.0         15676699  0015676699-1664815311-e8392778410edeea
6     15.0         15721545  0015721545-1664817441-cc2b8a83d78fb0e3

                  preco_id  cobertura_id  usuario_id  corretora_id  \
grupo categoria
0     15.0       327535618      16830520       14688          7799
1     9.0        327321373      16820418       22777         11747
      15.0       327321199      16820418       22777         11747
4     15.0       327360655      13554483        9490          4992
6     15.0       327380142      16823218       16364          8421

                 cliente_id  ranking  REFERENCIA  tempo  ... desv_da_media  \
grupo categoria                                          ...
0     15.0          1392675        2          61      3  ...     -0.566997
1     9.0           4457300       12          16     15  ...     -0.512430
      15.0          4457300        3          61      3  ...     -0.590656
4     15.0           843197        3          30     17  ...     -0.358735
6     15.0          2169849        2          20     12  ...     -0.291334

                probabilidade seguradora preco_caro preco_barato preco_normal  \
grupo categoria
0     15.0           0.000002         61          0            0            1
1     9.0            0.000003         16          0            0            1
      15.0           0.000002         61          0            1            0
4     15.0           0.000005         30          0            1            0
6     15.0           0.000006         20          0            0            1

                (premio_ajustado, min) (premio_ajustado, max)  dist_min  \
grupo categoria
0     15.0                 2745.267368              5195.8545  0.471643
1     9.0                  2348.694000              3307.4010  0.289867
      15.0                 1276.335000              1804.8690  0.292838
4     15.0                  913.113000               948.2600  0.037065
6     15.0                 3836.470000              3975.1900  0.034896

                 desv_med
grupo categoria
0     15.0       0.566997
1     9.0        0.512430
      15.0       0.590656
4     15.0       0.358735
6     15.0       0.291334

[5 rows x 111 columns]

In [299]:
merged_df = pd.merge(df_filtered3_filtrados_min, df_filtered2_filtrados[['preco_id', 'preco_validado', 'grupo', 'categoria']], on=['grupo', 'categoria', 'preco_id'], suffixes=('_left', '_right'))

In [300]:
merged_df.head(10)

,grupo,categoria,id_cotacao,grupo_calculo,preco_id,cobertura_id,usuario_id,corretora_id,cliente_id,ranking,...,probabilidade,seguradora,preco_caro,preco_barato,preco_normal,"(premio_ajustado, min)","(premio_ajustado, max)",dist_min,desv_med,preco_validado
0,0,15.0,13296967,0013296967-1664831874-5127bd118ec1b3f9,327535618,16830520,14688,7799,1392675,2,...,1.958303e-06,61,0,0,1,2745.267368,5195.854500,0.471643,0.566997,nao_validado
1,1,9.0,15642675,0015642675-1664808668-d4864d0f8a8eb584,327321373,16820418,22777,11747,4457300,12,...,2.596188e-06,16,0,0,1,2348.694000,3307.401000,0.289867,0.512430,nao_validado
2,1,15.0,15642675,0015642675-1664808668-d4864d0f8a8eb584,327321199,16820418,22777,11747,4457300,3,...,1.717661e-06,61,0,1,0,1276.335000,1804.869000,0.292838,0.590656,nao_validado
3,4,15.0,15676699,0015676699-1664815311-e8392778410edeea,327360655,13554483,9490,4992,843197,3,...,4.928360e-06,30,0,1,0,913.113000,948.260000,0.037065,0.358735,validado
4,6,15.0,15721545,0015721545-1664817441-cc2b8a83d78fb0e3,327380142,16823218,16364,8421,2169849,2,...,6.078474e-06,20,0,0,1,3836.470000,3975.190000,0.034896,0.291334,validado
5,7,15.0,15726031,0015726031-1664815396-a9061ce93538f574,327361425,16822322,16364,8421,3403630,2,...,4.972006e-06,20,0,0,1,4513.450000,4685.400000,0.036699,0.356159,validado
6,8,15.0,15777927,0015777927-1664816757-3d55030ebd06fbe3,327373086,16822884,16364,8421,2807678,1,...,7.922929e-06,18,1,0,0,22030.362000,25845.579000,0.147616,0.171806,validado
7,9,15.0,17446515,0017446515-1664818285-d5a6955f67af8d97,327390491,15450067,30939,18536,6346700,3,...,2.969369e-06,61,0,1,0,1454.722105,1825.673684,0.203186,0.484282,nao_validado
8,10,15.0,17719367,0017719367-1664804705-393dd7e6166051bc,327275529,16818279,22028,11315,6050227,2,...,8.380881e-07,61,0,1,0,1258.092000,2421.198000,0.480385,0.706241,nao_validado
9,12,15.0,18021105,0018021105-1664799733-ed099756be0a092f,327228239,16066872,26098,14558,4261257,13,...,8.946839e-06,22,1,0,0,5649.872000,5799.180000,0.025746,0.064252,validado

In [301]:
# # Set 'seguradora' as 'REFERENCIA'
# merged_df['seguradora'] = merged_df['REFERENCIA']

# # Group by 'seguradora'
# por_seguradora2 = merged_df.groupby('seguradora')

# # Create scatter plot for each 'seguradora'
# for seguradora, df_seguradora in por_seguradora2:
#         # Set color based on values in 'preco_validado' column
#         colors = []
#         for index, row in df_seguradora.iterrows():
#             if 'preco_validado' in row and row['preco_validado'] == 'validado':
#                 colors.append('green')
#             else: 
#                 colors.append('red')
#         # Create scatter plot
#         fig = px.scatter(df_seguradora, x='desv_med', y='dist_min', color=colors, color_discrete_map={'green': 'green', 'red': 'crimson'})
#         fig.update_layout(title=str(seguradora))
#         fig.show()

In [302]:
df_filtered2_filtrados.shape

(148360, 111)

In [303]:
# Group the DataFrame by 'seguradora' and count the quantity of rows with 'nao_validado' in 'preco_validado'
count_validado_seguradora = df_filtered2_filtrados.loc[df_filtered2_filtrados['preco_validado'] == 'nao_validado'].groupby('seguradora')['preco_validado'].count()

# Display the count for each 'seguradora'
print(count_validado_seguradora)

seguradora
11      10
12     400
13     331
15     139
16     684
18    4067
20       7
22     822
24     414
25     131
26    1402
27      35
30    1181
32     121
60      89
61    4409
Name: preco_validado, dtype: int64

In [304]:
# Group the DataFrame by 'seguradora' and count the quantity of rows with 'nao_validado' in 'preco_validado'
count_min_seguradora = df_filtered2_filtrados.groupby('seguradora').count()

# Display the count for each 'seguradora'
print(count_min_seguradora)

            id_cotacao  grupo_calculo  preco_id  cobertura_id  usuario_id  \
seguradora
11                6059           6059      6059          6059        6059
12               24197          24197     24197         24197       24197
13                4884           4884      4884          4884        4884
15                 598            598       598           598         598
16                3693           3693      3693          3693        3693
18               21623          21623     21623         21623       21623
20               39902          39902     39902         39902       39902
22                6804           6804      6804          6804        6804
24                2121           2121      2121          2121        2121
25                1221           1221      1221          1221        1221
26                8406           8406      8406          8406        8406
27                 277            277       277           277         277
30                9583           9583      9583          9583        9583
32                3467           3467      3467          3467        3467
60                 482            482       482           482         482
61               15043          15043     15043         15043       15043

            corretora_id  cliente_id  ranking  REFERENCIA  tempo  ...  grupo  \
seguradora                                                        ...
11                  6059        6059     6059        6059   6059  ...   6059
12                 24197       24197    24197       24197  24197  ...  24197
13                  4884        4884     4884        4884   4884  ...   4884
15                   598         598      598         598    598  ...    598
16                  3693        3693     3693        3693   3693  ...   3693
18                 21623       21623    21623       21623  21623  ...  21623
20                 39902       39902    39902       39902  39902  ...  39902
22                  6804        6804     6804        6804   6804  ...   6804
24                  2121        2121     2121        2121   2121  ...   2121
25                  1221        1221     1221        1221   1221  ...   1221
26                  8406        8406     8406        8406   8406  ...   8406
27                   277         277      277         277    277  ...    277
30                  9583        9583     9583        9583   9583  ...   9583
32                  3467        3467     3467        3467   3467  ...   3467
60                   482         482      482         482    482  ...    482
61                 15043       15043    15043       15043  15043  ...  15043

            categoria  filtro  (premio_ajustado, mean)  desv_da_media  \
seguradora
11               6059    6059                     6059           6059
12              24197   24197                    24197          24197
13               4884    4884                     4884           4884
15                598     598                      598            598
16               3693    3693                     3693           3693
18              21623   21623                    21623          21623
20              39902   39902                    39902          39902
22               6804    6804                     6804           6804
24               2121    2121                     2121           2121
25               1221    1221                     1221           1221
26               8406    8406                     8406           8406
27                277     277                      277            277
30               9583    9583                     9583           9583
32               3467    3467                     3467           3467
60                482     482                      482            482
61              15043   15043                    15043          15043

            probabilidade  preco_caro  preco_barato  preco_normal  \
seguradora
11                   6059        6059          6059          6059
12                  24197       24197         24197         24197
13                   4884        4884          4884          4884
15                    598         598           598           598
16                   3693        3693          3693          3693
18                  21623       21623         21623         21623
20                  39902       39902         39902         39902
22                   6804        6804          6804          6804
24                   2121        2121          2121          2121
25                   1221        1221          1221          1221
26                   8406        8406          8406          8406
27                    277         277           277           277
30                   9583        9583          9583          9583
32                   3467        3467          3467          3467
60                    482         482           482           482
61                  15043       15043         15043         15043

            preco_validado
seguradora
11                    6059
12                   24197
13                    4884
15                     598
16                    3693
18                   21623
20                   39902
22                    6804
24                    2121
25                    1221
26                    8406
27                     277
30                    9583
32                    3467
60                     482
61                   15043

[16 rows x 110 columns]

In [305]:
df_filtered3_filtrados_min.shape[0].

SyntaxError: invalid syntax (577031523.py, line 1)

In [ ]:
# Group the DataFrame by 'seguradora' and count the quantity of rows with 'nao_validado' in 'preco_validado'
count_minm_seguradora = df_filtered3_filtrados_min.groupby('seguradora')['preco_id'].count()

# Display the count for each 'seguradora'
print(count_minm_seguradora)

seguradora
11    1125
12    1623
13     220
15     120
16     714
18    1575
20     526
22     285
24     358
25      63
26     255
27      41
30    1545
32     584
60      78
61    5744
Name: preco_id, dtype: int64